name: kartowniczek
description: Kartowniczek to aplikacja ułatwiająca śledzenie przebiegu odbywającej się fizycznie gry karcianej. Pożegnaj kartkę papieru i długopis! Wpisz wartości, a kartowniczek podliczy punkty i przechowa dla ciebie zapis gry. Obecnie obsługiwane gry to tysiąc i kent.

publish_to: 'none'

version: 1.3.2
#historia wersji:
#1.0.0
#1.1.0
#1.1.1
#1.2.0
#1.2.1
#1.3.1
#1.3.2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
